"""
The renderer.

A playbook stored as JSON is perfect for machines but useless for the human SME
(Subject Matter Expert) who has to approve it. The renderer turns the structured
playbook back into things a human can read and eyeball in seconds:

  1. A Markdown document — each step, its guidance, its compliance tag, and the
     exact SOP sentence it came from (the citation).
  2. A Mermaid flow diagram — a picture of the graph, so the reviewer can *see*
     the flow and its branches instead of tracing ids in their head.

Mermaid is a plain-text way to describe diagrams that renders as a picture in
GitHub, most docs tools, and this chat. So the renderer's diagram output is just
text, but it draws as a real flowchart wherever Mermaid is supported.
"""

from __future__ import annotations

from playbook_forge.schema import Playbook, Step, StepType

# A little visual vocabulary so the diagram is readable at a glance.
_SHAPE = {
    StepType.VERIFY: ("([", "])"),    # stadium
    StepType.COLLECT: ("[", "]"),     # rectangle
    StepType.CONFIRM: ("([", "])"),   # stadium
    StepType.ACTION: ("[[", "]]"),    # subroutine box (the consequential ones)
    StepType.BRANCH: ("{", "}"),      # diamond (decision)
    StepType.INFORM: ("[", "]"),
    StepType.ESCALATE: ("[/", "/]"),  # parallelogram
}


def _safe(text: str) -> str:
    """Escape characters that would break Mermaid label parsing."""
    return text.replace('"', "'").replace("\n", " ").strip()


def to_mermaid(playbook: Playbook) -> str:
    """Render the playbook graph as a Mermaid flowchart."""
    lines = ["flowchart TD"]

    # Declare each node with a shape that reflects its type, and a label that
    # includes the compliance tag so gates stand out visually.
    for step in playbook.steps:
        open_b, close_b = _SHAPE.get(step.type, ("[", "]"))
        tag = f" ⚑{step.compliance_tag}" if step.compliance_tag else ""
        label = _safe(f"{step.title}{tag}")
        lines.append(f'    {step.id}{open_b}"{label}"{close_b}')

    # Mark the entry point.
    lines.append(f"    start((Start)) --> {playbook.entry_step_id}")

    # Draw the edges.
    for step in playbook.steps:
        if step.type == StepType.BRANCH:
            for br in step.branches:
                lines.append(f'    {step.id} -->|"{_safe(br.condition)}"| {br.next_step_id}')
        elif step.next:
            lines.append(f"    {step.id} --> {step.next}")
        else:
            # Terminal step: point to an End node so the diagram closes cleanly.
            lines.append(f"    {step.id} --> done((End))")

    # Highlight compliance gates with a class so they pop in a rendered diagram.
    gates = [s.id for s in playbook.steps if s.compliance_tag and s.required]
    if gates:
        lines.append("    classDef gate stroke:#c00,stroke-width:2px;")
        lines.append(f"    class {','.join(gates)} gate;")

    return "\n".join(lines)


def _citation_block(step: Step) -> str:
    if not step.source_citation:
        return "_(no citation — flag for review)_"
    loc = f" ({step.source_citation.location})" if step.source_citation.location else ""
    return f'> "{step.source_citation.quote}"{loc}'


def to_markdown(playbook: Playbook) -> str:
    """Render the playbook as a human-review document."""
    md: list[str] = []
    m = playbook.metadata
    md.append(f"# {playbook.title}")
    md.append("")
    md.append(f"**Intent:** `{playbook.intent}`  ")
    md.append(f"**Source SOP:** {m.source_document}  ")
    md.append(f"**Regulated:** {'yes' if m.regulated else 'no'}  ")
    md.append(f"**Generated by:** {m.generated_by}  ")
    md.append(f"**Version:** {m.version}")
    md.append("")
    if playbook.description:
        md.append(playbook.description)
        md.append("")

    md.append("## Flow diagram")
    md.append("")
    md.append("```mermaid")
    md.append(to_mermaid(playbook))
    md.append("```")
    md.append("")

    md.append("## Steps")
    md.append("")
    for i, step in enumerate(playbook.steps, 1):
        gate = f"  ·  🔒 **{step.compliance_tag}**" if step.compliance_tag else ""
        req = "required" if step.required else "optional"
        md.append(f"### {i}. {step.title}")
        md.append("")
        md.append(f"`{step.id}` · type: **{step.type.value}** · {req}{gate}")
        md.append("")
        md.append(f"**Agent guidance:** {step.agent_prompt}")
        md.append("")
        if step.preconditions:
            md.append(f"**Must happen after:** {', '.join(f'`{p}`' for p in step.preconditions)}")
            md.append("")
        if step.type == StepType.BRANCH and step.branches:
            md.append("**Branches:**")
            for br in step.branches:
                md.append(f"- if _{br.condition}_ → `{br.next_step_id}`")
            md.append("")
        elif step.next:
            md.append(f"**Next:** `{step.next}`")
            md.append("")
        else:
            md.append("**Next:** _(end of playbook)_")
            md.append("")
        md.append("**Source in SOP:**")
        md.append(_citation_block(step))
        md.append("")

    return "\n".join(md)
